{{- if .Values.sa.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}
  labels:
   app: {{ include "logging-agent.fullname" . }}
{{- end }}