{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  resourceNames:
  - {{ .Values.psp.name }}
  verbs: ['use']
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/logs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
roleRef:
  kind: ClusterRole
  apiGroup: {{ .Values.clusterRole.apiGroup }}
  name: {{ .Values.clusterRole.name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}
{{- end }}